### ISSUE TITLE
Start position projectile doesn't update

### ISSUE THREAD

**Issue by ghost** [Varkalandar/tiny_places#2] opened 2020-04-03 15:51 UTC
After shooting a projectile for the first time, no matter what position you're in next; it will fire from that exact position.

![tiny_places_1](https://user-images.githubusercontent.com/1148379/78380096-dd973180-75c2-11ea-9396-2e66d8f90db4.png)

**Comment by Varkalandar** [comment] 2020-04-10 23:33
It took a while to reproduce this. But just today I had the same effect. It happens when the actions list on the server is modified while processing - Java throws an exception in that case and this kept the server from updating the player position, while the client still moved the player avatar.

I hope that this is fixed with commit 515dbe3fae2328b84cccee0f01d30552d1e2f3a3 but since it happened so seldom on my system I cannot be 100% right now.

**Closed as completed by Varkalandar** 2020-04-10 23:33 UTC
